### PR TITLE
Mapzen Search geocoder handler

### PR DESCRIPTION
**Pull request by gandhiano**
This pull request adds a geocoder_handler for the Mapzen Search API (relates to https://www.drupal.org/node/2722577)

### CODE REVIEW

**Comment by drupol** [comment]
Looks good :-)

Could you please squash your commits into a single commit so I'll merge asap ?

Thanks.

**Comment by gandhiano** [comment]
Since recently it is possible for repository admins to [do this directly via the GitHub UI](https://github.com/blog/2141). Would you do it?

**Comment by gandhiano** [comment]
Cross-linking with related issues on Drupal for [geocoder](https://www.drupal.org/node/2722577) and [Open Atrium](https://www.drupal.org/node/2722713).

**Comment by drupol** [comment]
thanks ! :+1:

**Pull request merged**
