### PR TITLE
Added hook_update_n to update third party settings in geofield fields.

### PR DESCRIPTION
**Pull request by zsnagy73**
I noticed that the third party settings have also changed in the geofields that use geocoder. This update hook should add the new settings.

### CODE REVIEW

**Comment by itamair** [comment]
Tnx ... but,
Which is the downside of not performing this update updating the code from the alpha installation?
The Geocode and Reverse Geocode operations already set in both Field Widget and Formatters should work anyway without any crash or notices/warnings, isn't it?
Their configuration will be updated to the latest schema once the user performs a manual / backend update of their settings, I guess.
I will review this scenario asap anyway

**Comment by zsnagy73** [comment]
I got here from our issue with the parade module: https://www.drupal.org/project/parade/issues/2937618
We had to update our configs in order to be able to save nodes.

**Comment by drupol** [comment]
Ok @itamair,

I leave this in your hands then.

**Comment by itamair** [comment]
I don't think this merge should be run, because the actual dev has already gone far away and the new beta2 will have further different configurations and schema from beta2.
I explained here more and provided an Update Instructions issue with patch:
https://www.drupal.org/project/geocoder/issues/2936857#comment-12437028

**Pull request closed without merging**
